services:
  - type: web
    name: dynamic-nomogram-app
    runtime: r
    env: shiny
    buildCommand: R -e "install.packages('shiny')"
    startCommand: R -e "shiny::runApp('my_app', host='0.0.0.0', port=8080)"